version: '3'
services:
  homeassistant:
    container_name: ${HA_NAME}
    image: "ghcr.io/home-assistant/home-assistant:${HA_VERSION}"
    network_mode: host
    volumes:
      - ${INTERNAL_CONTAINERS_PATH:?}/${BASE_PATH:?}/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /dev:/dev
    restart: unless-stopped
    group_add:
      - dialout
    devices:
      - /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_ba955a46eda5ed11b859e9a32981d5c7-if00-port0:/dev/ttyUSB0